### ISSUE TITLE
Interface Issues

### ISSUE THREAD

**Issue by swalker2m** [gemini-hlsw/lucuma-odb#1023]
The query:

```graphql
query {
  observation(observationId: "o-151") {
    execution {
      config(futureLimit: 100) {
        ... on GmosNorthExecutionConfig {
          static {
            stageMode
            detector
          }
        }
        ... on GmosSouthExecutionConfig {
          static {
            stageMode
            detector
          }
        }
      }
    }
  }
}
```

Produces: 

![image_720](https://github.com/gemini-hlsw/lucuma-odb/assets/4906023/3ffbcddb-d622-4543-9730-5a8ad75f493d)

**Comment by swalker2m** [comment]
Check #1024 to see this problem in action.

**Comment by swalker2m** [comment]
Discussion with Miles indicates that the query / schema violate the spec and Grackle is now conforming to it whereas before it was not.  The issue as I understand it is that two concrete implementation of an interface cannot have leaf fields (at least) with the same name and yet with different types.  This despite the fact that the fields are not part of the interface itself.  So in this case we have `stageMode: GmosNorthStageMode!` in `GmosNorthStatic` and `stageMode: GmosSouthStageMode!` in `GmosSouthStatic`, which don't even share an interface but appear in `GmosNorthExecutionConfig` and `GmosSouthExecutionConfig` both of which implement `ExeuctionConfig`.

```
interface ExecutionConfig {
  instrument: Instrument!
}

type GmosNorthExecutionConfig implements ExecutionConfig {
  static: GmosNorthStatic!
  ...
}

type GmosSouthExecutionConfig implements ExecutionConfig {
  static: GmosSouthStatic!
  ...
}

type GmosNorthStatic {
  stageMode: GmosNorthStageMode!
  ...
}

type GmosSouthStatic {
  stageMode: GmosSouthStageMode!
  ...
}
```

**Comment by swalker2m** [comment]
To me this seems to render `interface`s dangerously unusable.  When you make a concrete `interface` implementation you have to check all other implementations and ensure that you've invented unique names for the fields which have differing types.

**Comment by swalker2m** [comment]
So one solution would be to ban interfaces, at least where this is likely to be a problem as in the case of `ExecutionConfig`. If we do this, `ExecutionConfig` would become a type with optional fields, all but one of which will always be `null`.

```
type ExecutionConfig {
  gmosNorth: GmosNorthExecutionConfig
  gmosSouth: GmosSouthExecutionConfig
  ghost: GhostExecutionConfig
 ....
}

**Comment by toddburnside** [comment]
I agree that the spec seems to wrong in this case. There seems no good reason to require fields of the same name that aren't in the interface to be of the same type. Seems to violate normal expectations of interfaces.

**Comment by swalker2m** [comment]
Another solution, I think is to dump it on the client and require aliasing the field names.  But that seems like it would lead naive API users (such as myself) to write what looks like a perfectly valid query as in the issue description.  From the error it might be hard to see what is wrong.

**Comment by toddburnside** [comment]
> In this particular case we could instead rename all the implementation-specific fields at the highest level and work around the issue, I think:

IMO, making unique names for all of the fields is uglier and hides some common intent. I don't think the interface provides enough usefulness in this case to warrant that.

**Comment by toddburnside** [comment]
> Another solution, I think is to dump it on the client and require aliasing the field names. But that seems like it would lead naive API users (such as myself) to write what looks like a perfectly valid query as in the issue description. From the error it might be hard to see what is wrong.

This would be fairly easy to implement in our clients since the relevant query (for this instance) is in `lucuma-schemas`. Just need to adjust the queries and the decoders. But I agree that API users may find the error less than helpful.

**Comment by rpiaggio** [comment]
I was going to suggest using union types, but then found out that they have the same restriction as interfaces.

> Another solution, I think is to dump it on the client and require aliasing the field names. But that seems like it would lead naive API users (such as myself) to write what looks like a perfectly valid query as in the issue description. From the error it might be hard to see what is wrong.

I lean towards this solution. Can we provide better error messages?

**Comment by toddburnside** [comment]
> I lean towards this solution. Can we provide better error messages?

I assume Miles could at least add to the message. Maybe suggest aliasing fields of the same name with different types?

**Comment by swalker2m** [comment]
There are a number of other cases that will need to be adjusted similarly.  I see at least `Atom`, `Step`, `StepRecord`, and `Visit` but there are other `interface`s as well that we might want to either do away with or change the field names.  `ProposalClass` seems like it could inadvertently evolve to have this problem.

**Comment by toddburnside** [comment]
> I lean towards this solution. Can we provide better error messages?

I think with a better error message, putting the burden on the API users to provide unique names seems like it might be the best approach.

**Comment by milessabin** [comment]
Is there any possibility of aligning the field types?

**Comment by swalker2m** [comment]
> Is there any possibility of aligning the field types?

Unfortunately no.  There will be quite a few instruments with distinct filter enumerations for example.  Or do you mean introduce a `union` of all the possibilities in each case?  For this example:

```
union GmosStageMode = GmosNorthStageMode | GmosSouthStageMode
```

Still I think that's going to be cumbersome.

**Comment by rpiaggio** [comment]
> There are a number of other cases that will need to be adjusted similarly. I see at least `Atom`, `Step`, `StepRecord`, and `Visit` but there are other `interface`s as well that we might want to either do away with or change the field names. `ProposalClass` seems like it could inadvertently evolve to have this problem.

Most of the queries for these types are also in a single choke point in lucuma-schemas. For UI development, it just means fixing the queries and subqueries there and the decoders accordingly.

**Comment by milessabin** [comment]
Both `GmosNorthStageMode` and `GmosSouthStageMode` are scalars, right?

How did you choose which decoder to use in the response to the query at the top of this issue before the fix for the Grackle bug landed? I'm puzzled because whichever of `GmosNorthExecutionConfig` or `GmosSouthExecutionConfig` is returned the shape of the response json would be the same, so presumably you're able to detect the type based on detail of the serialized form of the scalar? But if that's case then it seems that you ought to be able to construct an unambiguous scalar representation which encompasses both?

**Comment by milessabin** [comment]
Where I'm heading with the previous question is that I'm thinking that maybe the client in this context doesn't care about the precise type, and just needs a uniform String representation to display. In which case why not leave things as they are and just add,

```graphql
type GmosNorthStatic {
  stageMode: GmosNorthStageMode!
  displayStageMode: String!
  ...
}

type GmosSouthStatic {
  stageMode: GmosSouthStageMode!
  displayStageMode: String!
  ...
}
```
As a added bonus that could live in the interface, so you might not need the inline fragments at all.

**Comment by milessabin** [comment]
If `String` is too horrible you could have,
```graphql
scalar GmosNorthStageMode
scalar GmosSouthStageMode

scalar GmosDisplayStageMode

type GmosNorthStatic {
  stageMode: GmosNorthStageMode!
  displayStageMode: GmosDisplayStageMode!
  ...
}

type GmosSouthStatic {
  stageMode: GmosSouthStageMode!
  displayStageMode: GmosDisplayStageMode!
  ...
}
```

**Comment by toddburnside** [comment]
> As a added bonus that could live in the interface, so you might not need the inline fragments at all.

Some instruments will have a stageMode, etc., others will not.

**Comment by swalker2m** [comment]
The stage modes are enumerations.  Looking at them, they actually match (though they shouldn't) so this isn't the best example.  We might be able to unify the `static` fields for GMOS but it won't solve the general problem.

**Comment by toddburnside** [comment]
> How did you choose which decoder to use in the response to the query at the top of this issue before the fix for the Grackle bug landed?

Currently, we are decoding the Instrument first, then using that to determine how to decode the rest of it. The instrument is part of the interface. (There is more to the actual query we use than the snippet above.)

**Comment by swalker2m** [comment]
I presume for the GMOS north vs south sequences, with their FPUs, Filters etc. we must include a `__typename`?  Or do we just try decoding it as GMOS north and then south, until one matches?

**Comment by toddburnside** [comment]
> I presume for the GMOS north vs south sequences, with their FPUs, Filters etc. we must include a `__typename`? Or do we just try decoding it as GMOS north and then south, until one matches?

It's all part of the same query, so we base it on the instrument in the config.

**Comment by milessabin** [comment]
To clarify things a little for me, is this an accurate summary of the situation?

You have many types which are,
1. structurally very similar (hence have multi-step common paths)
2. can be meaningfully returned via reference to a common interface type or as components of a union (hence need to be distinguished using an inline or other fragment)
3. despite (1) and (2), have differing leaf types, or non-leaf terminal subtrees, which mean that when following common paths, at some point the types differ.

I'm guessing that to represent these types in Scala you would use parametric polymorphism to capture the variation in a common interface for these?

**Comment by milessabin** [comment]
That helps, thanks.

A direct translation from an interface with type parameters to an interface without is always going to be tricky.

GraphQL will allow you to merge structurally similar types, so long as they agree on all the same-named leaf types. That gives you one other option that you might not have considered yet. You could replace all your conflicting _scalar_ types with _object_ types which _are_ mergeable. Instead of,

```graphql
type Query {
  instrument: Common
}

scalar Foo
scalar Bar

interface Common

type FooInstrument extends Common {
  thing: Foo
}

type BarInstrument extends Common {
  thing: Bar
}

query {
  instrument {
    ... on FooInstrument {
      thing  // Not mergeable
    }
    ... on BarInstrument {
      thing  // Not mergeable
    }
}
```
You could instead have,
```graphql
type Query {
  instrument: Common
}

scalar Foo
scalar Bar
scalar CommonLeaf // scalar that can represent both Foo and Bar

type FooWrapper {
  foo: Foo
  common: CommonLeaf
}
type BarWrapper {
  bar: Bar
  common: CommonLeaf
}

interface Common

type FooInstrument extends Common {
  thing: Foo
  wrappedThing: FooWrapper
}

type BarInstrument extends Common {
  thing: Bar
  wrappedThing: BarWapper
}

query {
  instrument {
    ... on FooInstrument {
      wrappedThing {
        common // Mergeable
      }
    }
    ... on BarInstrument {
      wrappedThing {
        common // Mergeable
      }
    }
}
```
What's happening here is that you're trading opaque scalars for structured types which have fields which support unification across the family. I've preserved the original unwrapped fields, but if that isn't necessary you could simplify things by leaving them out.

I don't know if that's helpful your scenario.

**Comment by toddburnside** [comment]
> I don't know if that's helpful in your scenario.

Thanks for the suggestion, but that would add a lot of layers to the already deep trees. I think we'll just skip the interface part.

**Comment by milessabin** [comment]
> but that would add a lot of layers to the already deep trees

It would only add one more layer, immediately above scalars at the leaves.

Anyhow, I'll stop flogging this dead horse now ...

**Comment by milessabin** [comment]
@rpiaggio GraphQL doesn't support unions of scalars ... that's the root of your problem (rather than interfaces, which are blameless IMO).

**Comment by swalker2m** [comment]
https://github.com/gemini-hlsw/lucuma-odb/pull/1032
