### ISSUE TITLE
Add `group` root query

### ISSUE THREAD

**Issue by hugo-vrijswijk** [gemini-hlsw/lucuma-odb#1057]
Currently the only way to query for groups is by querying `program.allGroupElements`. Similar to program or observation, it would be useful to be able to query for a single group. This would help in querying only the program times for groups that have changed (on updates) in Explore:

```graphql
query ($groupId: GroupId!) {
  group(groupId: $groupId) {
    id
    timeEstimateRange {
      minimum {
        program {
          microseconds
        }
      }
      maximum {
        program {
          microseconds
        }
      }
    }
  }
}

```

**Comment by swalker2m** [comment]
Fixed in #1058.
