### ISSUE TITLE
Switch CfP fails even if type set to null

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/lucuma-odb#1210]
This mutation:

```graphql
mutation($input: UpdateProposalInput!) {
  updateProposal(input: $input) {
    proposal {
      title
  	}
  }
}
```
variables:
```json
        "input": {
            "programId": "p-100",
            "SET": {
                "callId": "c-102",
                "type": null
            }
        }
```
fails when the proposal type is incompatible even though we explicitly pass a null type in the variable

and gives a result:
```json
{
  "errors": [
    {
      "message": "The Call for Proposals c-102 is a Fast Turnaround call and cannot be used with a Queue proposal.",
      "extensions": {
        "odb_error": {
          "odb_error.tag": "invalid_argument",
          "odb_error.detail": "The Call for Proposals c-102 is a Fast Turnaround call and cannot be used with a Queue proposal.",
          "odb_error.data": {}
        }
      }
    }
  ],
  "data": null
}
```

**Comment by swalker2m** [comment]
For better or worse, this is as designed.  When you change the Call for Proposals, you have to supply the fields for the type corresponding to the call.  It cannot be left empty or set to `null`.  So if you picked an FT call you set the type:

```
type: {
  fastTurnaround: {
    ...
  }
}
```

**Comment by cquiroz** [comment]
Ok, got it

**Comment by swalker2m** [comment]
I think most, if not all the properties have defaults though so you may not need to specify anything else.

**Comment by cquiroz** [comment]
calling the query above without a type gives a similar error. at least when starting from a regular cfp

**Comment by cquiroz** [comment]
Do we have a definition of the defaults forr each proposal type?

**Comment by swalker2m** [comment]
The defaults are:

```scala
    tooActivation:   ToOActivation            = ToOActivation.None,
    minPercentTime:  IntPercent               = HundredPercent,
    minPercentTotal: Option[IntPercent]       = none,
    totalTime:       Option[TimeSpan]         = none,
    partnerSplits:   Map[Partner, IntPercent] = Map.empty
```

but for Large Program 

```scala
              _ <- minPercentTotal := minTotal.orElse(HundredPercent.some)
              _ <- totalTime       := total.orElse(TimeSpan.Zero.some)
```

Fast Turnaround has a single `piAffiliation` but that is kept as a `PartnerSplits` map just the same in which there is one entry with 100% (when it is eventually set).

**Comment by cquiroz** [comment]
This was fixed on explore making sure we set the proposal type
