### ISSUE TITLE
Include parent information on groupEdit subscription

### ISSUE THREAD

**Issue by hugo-vrijswijk** [gemini-hlsw/lucuma-odb#439]
This is so we can update Explore correctly when, for example, a group is moved. Both `parentGroup` and `parentGroupIndex` would be need to be included

**Comment by tpolecat** [comment]
Would it be sufficient to add parentGroup and parentIndex on the group `value`? i.e., you would ask for

```graphl
{
  editType
  value {
    parentId
    parentIndex
    ...
  }
}
```

**Comment by hugo-vrijswijk** [comment]
I think that would be sufficient, yes
