### ISSUE TITLE
Missing observation events

### ISSUE THREAD

**Issue by swalker2m** [gemini-hlsw/lucuma-odb#445]
There is a table per science mode.  An example is `t_gmos_north_long_slit`.  Each references the observation with which it should be associated.  @cquiroz  reports that edits to those tables do not generate observation update events.  Logically changing mode parameters is an observation edit.  Perhaps we need to add a trigger on these tables (currently just `t_gmos_north_long_slit` and `t_gmos_south_long_slit`)?

**Comment by tpolecat** [comment]
@cquiroz I wrote a test for this and it passes … can you still reproduce in Explore? Maybe it got fixed inadvertently.

**Comment by cquiroz** [comment]
The one case I remember is when editing the offsets we wouldn't see an event with the updated offsets to display.

I just tested it and it is now working as expected

**Comment by swalker2m** [comment]
This seems to be working now.
